name: Terraform  Workflow new2

on:
  push:
    branches:
      - main
      - master

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Print directory structure
        run: ls -R

      - name: Check if Terraform directory exists
        run: ls -la Terraform  # Adjust this path as necessary

      - name: Initialize Terraform
        run: terraform init
        working-directory: Terraform  # Adjust this path as necessary

      - name: Apply Terraform
        run: terraform apply -auto-approve
        working-directory: Terraform  # Adjust this path as necessary
