name: Terraform Workflow

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print root directory structure
        run: ls -la /home/runner/work/Node-app/Node-app

      - name: Print detailed directory structure
        run: find /home/runner/work/Node-app/Node-app

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Initialize Terraform
        run: terraform init
        working-directory: /home/runner/work/Node-app/Node-app/terraform  # Adjust this path as necessary

      - name: Apply Terraform
        run: terraform apply -auto-approve
        working-directory: /home/runner/work/Node-app/Node-app/terraform  # Adjust this path as necessary
